### ISSUE TITLE
biomass_at_length_table multiple regions

### ISSUE THREAD

**Issue by nlauffenburger** [noaa-afsc-mace/MACEReports#24]
Can you add in the flexibility for the caption to use the region name instead of the hard-coded Shelifkof for this table?  This might also be helpful in the tables at age as well.  Numbers at length is already flexible.
Thanks!

**Comment by mike-levine** [comment]
Oh that's just an oversight on my part- my bad. I think I've got them all fixed now (limiting time to test but it's a simple change and it worked fine with my report- should work fine once the 'at-ages' tables are generated too.

Good catch. I'll push that now and close this, unless something is amiss when you update the package and run on your end.
